language: objective-c
osx_image: xcode7.1

script:
  - xcodebuild -project FormationLayout.xcodeproj -scheme FormationLayout -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
