language: objective-c
osx_image: xcode7.1
xcode_project: FormationLayout.xcodeproj
xcode_scheme: FormationLayout
xcode_sdk: iphonesimulator
branches:
  only:
    - master

install:
  - gem install slather -N
after_success: slather
